# Generated by Django 3.1.3 on 2020-12-09 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0009_likecommentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes1',
            field=models.ManyToManyField(related_name='liked_comments', through='manager.LikeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
